import { Lock, ShieldCheck, Server, KeyRound, FileClock, Database, Check } from "lucide-react";
import { Reveal } from "@/components/common/Reveal";
import { Eyebrow } from "@/components/common/SectionHeading";
const points = [
  { t: "Encryption", d: "TLS 1.3 in transit and AES-256 at rest for sessions and records." },
  { t: "DPDP Act 2023 compliant", d: "Controls designed for India’s data-protection requirements." },
  { t: "India data residency", d: "Candidate data stored in India on AWS Mumbai (ap-south-1)." },
  { t: "Access controls", d: "Role-based access and audit logs support accountable administration." },
];
const badges = [{ label: "TLS 1.3", Icon: Lock }, { label: "AES-256", Icon: KeyRound }, { label: "DPDP", Icon: ShieldCheck }, { label: "India region", Icon: Server }, { label: "RBAC", Icon: Database }, { label: "Audit logs", Icon: FileClock }];
export const Security = () => <section className="py-20 sm:py-28"><div className="container-xl"><div className="grid items-center gap-14 lg:grid-cols-2"><div><Reveal><Eyebrow>Security &amp; data protection</Eyebrow></Reveal><Reveal delay={.05}><h2 className="mt-5 max-w-lg font-display text-3xl font-bold sm:text-4xl">Candidate data stays protected</h2></Reveal><Reveal delay={.1}><p className="mt-4 max-w-lg text-base text-muted-foreground sm:text-lg">Protect interview records with encryption, accountable access, deletion controls, and hosting in India.</p></Reveal><div className="mt-8 grid gap-4 sm:grid-cols-2">{points.map(p=><div key={p.t} className="flex gap-3"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-success/12 text-success"><Check className="h-3.5 w-3.5" /></span><div><p className="text-sm font-semibold">{p.t}</p><p className="mt-1 text-sm text-muted-foreground">{p.d}</p></div></div>)}</div></div><Reveal><div className="rounded-[2rem] border border-border bg-card p-8 shadow-elegant"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-navy text-background"><Lock className="h-6 w-6" /></span><div><p className="font-display text-lg font-semibold">Hiring-team controls</p><p className="text-sm text-muted-foreground">Scoped to your company and roles.</p></div></div><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-3">{badges.map(({label,Icon})=><div key={label} className="flex flex-col items-center justify-center gap-2 rounded-xl border border-border bg-secondary/60 px-3 py-4 text-center text-sm font-semibold"><Icon className="h-5 w-5 text-primary" aria-hidden="true" />{label}</div>)}</div></div></Reveal></div></div></section>;
