/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechnicalInterviewRouteImport } from './routes/technical-interview'
import { Route as ResumeAnalyzerRouteImport } from './routes/resume-analyzer'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as EarlyAccessRouteImport } from './routes/early-access'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunicationAnalysisRouteImport } from './routes/communication-analysis'
import { Route as CodingInterviewRouteImport } from './routes/coding-interview'
import { Route as CareerCoachRouteImport } from './routes/career-coach'
import { Route as BookMeetingRouteImport } from './routes/book-meeting'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiInterviewRouteImport } from './routes/ai-interview'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicalInterviewRoute = TechnicalInterviewRouteImport.update({
  id: '/technical-interview',
  path: '/technical-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalyzerRoute = ResumeAnalyzerRouteImport.update({
  id: '/resume-analyzer',
  path: '/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyAccessRoute = EarlyAccessRouteImport.update({
  id: '/early-access',
  path: '/early-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationAnalysisRoute = CommunicationAnalysisRouteImport.update({
  id: '/communication-analysis',
  path: '/communication-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CodingInterviewRoute = CodingInterviewRouteImport.update({
  id: '/coding-interview',
  path: '/coding-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCoachRoute = CareerCoachRouteImport.update({
  id: '/career-coach',
  path: '/career-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BookMeetingRoute = BookMeetingRouteImport.update({
  id: '/book-meeting',
  path: '/book-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInterviewRoute = AiInterviewRouteImport.update({
  id: '/ai-interview',
  path: '/ai-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-interview': typeof AiInterviewRoute
  '/blog': typeof BlogRoute
  '/book-meeting': typeof BookMeetingRoute
  '/career-coach': typeof CareerCoachRoute
  '/coding-interview': typeof CodingInterviewRoute
  '/communication-analysis': typeof CommunicationAnalysisRoute
  '/contact': typeof ContactRoute
  '/early-access': typeof EarlyAccessRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/resources': typeof ResourcesRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/technical-interview': typeof TechnicalInterviewRoute
  '/terms': typeof TermsRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-interview': typeof AiInterviewRoute
  '/blog': typeof BlogRoute
  '/book-meeting': typeof BookMeetingRoute
  '/career-coach': typeof CareerCoachRoute
  '/coding-interview': typeof CodingInterviewRoute
  '/communication-analysis': typeof CommunicationAnalysisRoute
  '/contact': typeof ContactRoute
  '/early-access': typeof EarlyAccessRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/resources': typeof ResourcesRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/technical-interview': typeof TechnicalInterviewRoute
  '/terms': typeof TermsRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-interview': typeof AiInterviewRoute
  '/blog': typeof BlogRoute
  '/book-meeting': typeof BookMeetingRoute
  '/career-coach': typeof CareerCoachRoute
  '/coding-interview': typeof CodingInterviewRoute
  '/communication-analysis': typeof CommunicationAnalysisRoute
  '/contact': typeof ContactRoute
  '/early-access': typeof EarlyAccessRoute
  '/enterprise': typeof EnterpriseRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/resources': typeof ResourcesRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/technical-interview': typeof TechnicalInterviewRoute
  '/terms': typeof TermsRoute
  '/universities': typeof UniversitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-interview'
    | '/blog'
    | '/book-meeting'
    | '/career-coach'
    | '/coding-interview'
    | '/communication-analysis'
    | '/contact'
    | '/early-access'
    | '/enterprise'
    | '/faq'
    | '/features'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/resources'
    | '/resume-analyzer'
    | '/technical-interview'
    | '/terms'
    | '/universities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-interview'
    | '/blog'
    | '/book-meeting'
    | '/career-coach'
    | '/coding-interview'
    | '/communication-analysis'
    | '/contact'
    | '/early-access'
    | '/enterprise'
    | '/faq'
    | '/features'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/resources'
    | '/resume-analyzer'
    | '/technical-interview'
    | '/terms'
    | '/universities'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-interview'
    | '/blog'
    | '/book-meeting'
    | '/career-coach'
    | '/coding-interview'
    | '/communication-analysis'
    | '/contact'
    | '/early-access'
    | '/enterprise'
    | '/faq'
    | '/features'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/resources'
    | '/resume-analyzer'
    | '/technical-interview'
    | '/terms'
    | '/universities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiInterviewRoute: typeof AiInterviewRoute
  BlogRoute: typeof BlogRoute
  BookMeetingRoute: typeof BookMeetingRoute
  CareerCoachRoute: typeof CareerCoachRoute
  CodingInterviewRoute: typeof CodingInterviewRoute
  CommunicationAnalysisRoute: typeof CommunicationAnalysisRoute
  ContactRoute: typeof ContactRoute
  EarlyAccessRoute: typeof EarlyAccessRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  ResourcesRoute: typeof ResourcesRoute
  ResumeAnalyzerRoute: typeof ResumeAnalyzerRoute
  TechnicalInterviewRoute: typeof TechnicalInterviewRoute
  TermsRoute: typeof TermsRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technical-interview': {
      id: '/technical-interview'
      path: '/technical-interview'
      fullPath: '/technical-interview'
      preLoaderRoute: typeof TechnicalInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analyzer': {
      id: '/resume-analyzer'
      path: '/resume-analyzer'
      fullPath: '/resume-analyzer'
      preLoaderRoute: typeof ResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-access': {
      id: '/early-access'
      path: '/early-access'
      fullPath: '/early-access'
      preLoaderRoute: typeof EarlyAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-analysis': {
      id: '/communication-analysis'
      path: '/communication-analysis'
      fullPath: '/communication-analysis'
      preLoaderRoute: typeof CommunicationAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coding-interview': {
      id: '/coding-interview'
      path: '/coding-interview'
      fullPath: '/coding-interview'
      preLoaderRoute: typeof CodingInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-coach': {
      id: '/career-coach'
      path: '/career-coach'
      fullPath: '/career-coach'
      preLoaderRoute: typeof CareerCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-meeting': {
      id: '/book-meeting'
      path: '/book-meeting'
      fullPath: '/book-meeting'
      preLoaderRoute: typeof BookMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-interview': {
      id: '/ai-interview'
      path: '/ai-interview'
      fullPath: '/ai-interview'
      preLoaderRoute: typeof AiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiInterviewRoute: AiInterviewRoute,
  BlogRoute: BlogRoute,
  BookMeetingRoute: BookMeetingRoute,
  CareerCoachRoute: CareerCoachRoute,
  CodingInterviewRoute: CodingInterviewRoute,
  CommunicationAnalysisRoute: CommunicationAnalysisRoute,
  ContactRoute: ContactRoute,
  EarlyAccessRoute: EarlyAccessRoute,
  EnterpriseRoute: EnterpriseRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  ResourcesRoute: ResourcesRoute,
  ResumeAnalyzerRoute: ResumeAnalyzerRoute,
  TechnicalInterviewRoute: TechnicalInterviewRoute,
  TermsRoute: TermsRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
